// Auto-generated by scripts/generate_dsl_types.py
// DO NOT EDIT MANUALLY — regenerate with: python scripts/generate_dsl_types.py


export const ExecutionMode = {
  SERIAL: "SERIAL",
  PARALLEL: "PARALLEL",
} as const

export type ExecutionModeValue = "SERIAL" | "PARALLEL"

export const LoopType = {
  FOR: "FOR",
  WHILE: "WHILE",
  FOREACH: "FOREACH",
} as const

export type LoopTypeValue = "FOR" | "WHILE" | "FOREACH"

export const StepType = {
  SCRIPT: "SCRIPT",
  LOOP: "LOOP",
  CALL: "CALL",
} as const

export type StepTypeValue = "SCRIPT" | "LOOP" | "CALL"

export interface YamlLoop {
  id: string
  loop_type: LoopTypeValue
  steps?: Array<YamlStep | YamlLoop>
  count?: number | null
  condition?: string | null
  collection?: string | null
  iterator_var?: string | null
  execution_mode?: ExecutionModeValue
  max_iterations?: number
  skip_if?: string | null
}

export interface YamlPlan {
  name: string
  version: string
  scope?: Record<string, unknown>
  max_concurrency?: number
  steps?: Array<YamlStep | YamlLoop>
}

export interface YamlStep {
  id: string
  script: string
  params?: Record<string, unknown>
  preconditions?: Array<string>
  resources?: Record<string, unknown>
  timeout?: number
  retry?: number
  on_fail?: string | null
  export_outputs?: boolean
  skip_if?: string | null
}

/**
 * Frontend convenience types built on the canonical DSL schema.
 * YamlScope narrows YamlPlan.scope to the common { variables } pattern.
 * YamlSequence is the frontend's view of a YamlPlan for YAML serialization.
 */
export interface YamlScope {
  variables?: Record<string, unknown>
}

export interface YamlSequence {
  name: string
  version: string
  scope?: YamlScope
  max_concurrency?: number
  steps: Array<YamlStep | YamlLoop>
}
