"""SPC (Statistical Process Control) API endpoints.

Provides:
- ``GET /api/v1/spc/{product_type}/{measurement_name}`` - current SPC statistics
- ``GET /api/v1/spc/{product_type}/{measurement_name}/chart`` - X-bar/R chart data
- ``GET /api/v1/spc/alerts`` - recent SPC alerts

The statistics and chart endpoints load the most recent measurements from the
database, feed them into a per-request SPCProcessor (no shared state - the
numbers reflect the DB), and return computed indices and control-chart geometry.

The alerts endpoint surfaces alerts collected by a long-lived streaming
processor. When one is attached to ``app.state.spc_processor`` (by the lifespan
startup), its in-memory alert buffer is returned; when none is attached, the
endpoint returns an empty list - no alerts have been generated because no
streaming processor is running.
"""

from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ate_cloud.db import get_db
from ate_cloud.models.measurement import Measurement
from ate_cloud.schemas.spc import SPCAlert, SPCChart, SPCStatistics
from ate_cloud.services.spc import SPCProcessor

router = APIRouter(prefix="/spc", tags=["spc"])

# Type alias for async DB session dependency (avoids B008 ruff warning).
DBSession = Annotated[AsyncSession, Depends(get_db)]

#: How many recent measurements to load for SPC computation.
_DEFAULT_SAMPLE_LIMIT = 100


async def _load_processor(
    db: AsyncSession,
    product_type: str,
    measurement_name: str,
    limit: int,
) -> SPCProcessor:
    """Build an SPCProcessor seeded with the most recent measurements.

    Measurements are loaded newest-first then reversed so the sliding window
    reflects chronological order. The processor is per-request - it carries
    no state between calls.
    """
    result = await db.execute(
        select(Measurement)
        .where(
            Measurement.product_ref == product_type,
            Measurement.name == measurement_name,
            Measurement.value.is_not(None),
        )
        .order_by(Measurement.timestamp.desc())
        .limit(limit)
    )
    rows = list(result.scalars().all())
    rows.reverse()

    processor = SPCProcessor()
    for m in rows:
        processor.process_measurement(m)
    return processor


@router.get(
    "/{product_type}/{measurement_name}",
    response_model=SPCStatistics,
)
async def get_spc_statistics(
    product_type: str,
    measurement_name: str,
    db: DBSession,
    limit: int = Query(_DEFAULT_SAMPLE_LIMIT, ge=2, le=500),
) -> SPCStatistics:
    """Get current SPC statistics for a measurement stream.

    Args:
        product_type: Product type identifier.
        measurement_name: Measurement name.
        limit: Number of recent samples to consider (2-500, default 100).
        db: Database session.

    Returns:
        SPCStatistics with Cp, Cpk, Ppk, mean, sigmas, and sample count.
        Sample count is 0 when no measurements exist for the stream.
    """
    processor = await _load_processor(db, product_type, measurement_name, limit)
    return processor.get_statistics(product_type, measurement_name)


@router.get(
    "/{product_type}/{measurement_name}/chart",
    response_model=SPCChart,
)
async def get_spc_chart(
    product_type: str,
    measurement_name: str,
    db: DBSession,
    limit: int = Query(_DEFAULT_SAMPLE_LIMIT, ge=5, le=500),
) -> SPCChart:
    """Get X-bar / R control chart data for a measurement stream.

    Args:
        product_type: Product type identifier.
        measurement_name: Measurement name.
        limit: Number of recent samples to consider (5-500, default 100).
        db: Database session.

    Returns:
        SPCChart with center line, control limits, and subgroup statistics.
        Chart fields are null when fewer than one complete subgroup exists.
    """
    processor = await _load_processor(db, product_type, measurement_name, limit)
    return processor.get_chart(product_type, measurement_name)


@router.get("/alerts", response_model=list[SPCAlert])
async def get_spc_alerts(
    request: Request,
    limit: int = Query(50, ge=1, le=500),
) -> list[SPCAlert]:
    """Get recent SPC alerts from the streaming processor.

    Alerts are generated by the streaming SPCProcessor during measurement
    ingestion (not by the read endpoints above). This endpoint returns the
    alert buffer of the processor attached to ``app.state.spc_processor``.
    When no streaming processor is attached (e.g. dev mode without the
    lifespan wiring), an empty list is returned - no alerts have been
    generated because no processor is running.

    Args:
        limit: Maximum number of alerts to return (1-500, default 50).

    Returns:
        List of SPCAlert objects, newest first.
    """
    processor = getattr(request.app.state, "spc_processor", None)
    if processor is None:
        return []
    if not isinstance(processor, SPCProcessor):
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="app.state.spc_processor is not an SPCProcessor",
        )
    return processor.get_alerts(limit=limit)


__all__ = ["router"]
